

name: Discord Webhook Bot

on: workflow_dispatch

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: "{\"embeds\":[{\"title\":\"Meow!\",\"color\":1127128},{\"title\":\"Meow-meow!\",\"color\":14177041}]}"
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: 'Hello there!'
