

name: Discord Webhook Bot

on: workflow_dispatch

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title":"Meow!","color":1127128,"url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Black_Cat_%287983739954%29.jpg/1280px-Black_Cat_%287983739954%29.jpg"}]'
        uses: Ilshidur/action-discord@0.3.2
#         with:
#           args: 'Hello there!'
